### ISSUE TITLE
ImportError: cannot import name 'PasswordHasher' from 'argon2'

### ISSUE THREAD

**Issue by fabgilson** [adeyosemanputra/pygoat#158]
Hello team,

I cloned your `master` branch today, installed the requirements (following your method 2) and running `python3 manage.py migrate` complained first about `ModuleNotFoundError: No module named 'argon2'`. I manually installed it with `pip3 install argon2`, but then I received below error:
```
python3 manage.py migrate
Traceback (most recent call last):
  File "/home/fgi18/Documents/github/pygoat/pygoat/manage.py", line 21, in <module>
    main()
  File "/home/fgi18/Documents/github/pygoat/pygoat/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    self.check(databases=[database])
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/fgi18/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/fgi18/Documents/github/pygoat/pygoat/pygoat/urls.py", line 18, in <module>
    from introduction import views as v
  File "/home/fgi18/Documents/github/pygoat/pygoat/introduction/views.py", line 35, in <module>
    from argon2 import PasswordHasher
ImportError: cannot import name 'PasswordHasher' from 'argon2' (/home/fgi18/.local/lib/python3.10/site-packages/argon2.py)
```

My system is a Ubuntu 22.04, python 3.10.4.

Any idea?
Thanks,
Fabian

**Comment by fabgilson** [comment]
Hello,

Apologies for opening the issue before googling enough. A deeper search pointed me to the right direction. The missing import from your `requirements` file is `argon2-cffi`, not `argon2`.

Do you want me to open a pull a request?
Thanks!

**Comment by banstala** [comment]
Hello @fabgilson 

Your post nonetheless showed me to getting hold of the right module... which like you, I too missed out.

Thanks.

**Comment by adeyosemanputra** [comment]
> Hello,
> 
> Apologies for opening the issue before googling enough. A deeper search pointed me to the right direction. The missing import from your `requirements` file is `argon2-cffi`, not `argon2`.
> 
> Do you want me to open a pull a request? Thanks!

yes please
